#include "highgui.h"
#include "cv.h"
#include "opencv2/opencv.hpp"
#include <QWidget>
#include <QSpinBox>
#include <QPushButton>
#include <QStringListModel>
#include <QUdpSocket>
#include <QTcpSocket>
#include <QTimer>
#include <QDateTime>
#include <QProcess>
#include <QTranslator>
#include <qmessagebox.h>  //F1µ¯³ö¶Ô»°¿ò
#include <QFileDialog>
#include <QFile>
#include <QSettings>
#include <QPalette>
#include <QSqlQuery>
#include <QSqlRecord>
#include <QPainter>
#include <QDebug>
#include <QTextStream>
#include <QFile>
#include <QDomComment>
